// <auto-generated />
using System;
using CitusManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CitusManager.Data.Migrations
{
    [DbContext(typeof(ControlDbContext))]
    [Migration("20260817152614_AddTopologyQueryEndpoints")]
    partial class AddTopologyQueryEndpoints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CitusManager.Domain.AlertRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastNotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NotificationAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId", "Fingerprint", "State");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("CitusManager.Domain.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PreferredCulture")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CitusManager.Domain.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("DetailJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResourceId")
                        .HasColumnType("text");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("CitusManager.Domain.BackupDestinationCopy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("BackupRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ManifestCommitted")
                        .HasColumnType("boolean");

                    b.Property<string>("ObjectPrefix")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProtectedStorageSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderResumeStateJson")
                        .HasColumnType("text");

                    b.Property<string>("SafeError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StorageProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("StorageProfileVersion")
                        .HasColumnType("integer");

                    b.Property<long>("UploadedBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("UploadedObjects")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StorageProfileId");

                    b.HasIndex("BackupRunId", "StorageProfileId")
                        .IsUnique();

                    b.ToTable("BackupDestinationCopies");
                });

            modelBuilder.Entity("CitusManager.Domain.BackupRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ApplicationConsistent")
                        .HasColumnType("boolean");

                    b.Property<long>("ArchiveBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ArchiveSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<string>("CitusMetadataJson")
                        .HasColumnType("text");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentPhase")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DiagnosticTail")
                        .HasColumnType("text");

                    b.Property<long?>("EstimatedSourceBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<string>("ManifestHmac")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ManifestJson")
                        .HasColumnType("text");

                    b.Property<int>("ObjectCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<string>("PolicySnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProcessExitCode")
                        .HasColumnType("integer");

                    b.Property<long>("ProcessedBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("RequestedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RetriedFromRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SafeError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Trigger")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.HasIndex("RetriedFromRunId");

                    b.HasIndex("RetryAt");

                    b.HasIndex("ClusterId", "CreatedAt");

                    b.HasIndex("ClusterId", "Status");

                    b.ToTable("BackupRuns");
                });

            modelBuilder.Entity("CitusManager.Domain.BackupRunStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BackupRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("ProcessedBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("SafeError")
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long?>("TotalBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BackupRunId", "Sequence")
                        .IsUnique();

                    b.ToTable("BackupRunSteps");
                });

            modelBuilder.Entity("CitusManager.Domain.BackupTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EncryptionEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MinuteOfHour")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long>("ObjectSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("RetentionMaxAgeDays")
                        .HasColumnType("integer");

                    b.Property<int>("RetentionMaxBackups")
                        .HasColumnType("integer");

                    b.Property<int>("RetentionMinBackups")
                        .HasColumnType("integer");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("RunAtLocalTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("RunOnDayOfMonth")
                        .HasColumnType("integer");

                    b.Property<int>("RunOnDayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleInterval")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleUnit")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BackupTemplates");
                });

            modelBuilder.Entity("CitusManager.Domain.BackupTemplateNotification", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NotificationProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Events")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("TemplateId", "NotificationProfileId");

                    b.HasIndex("NotificationProfileId");

                    b.ToTable("BackupTemplateNotifications");
                });

            modelBuilder.Entity("CitusManager.Domain.BackupTemplateStorage", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StorageProfileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("TemplateId", "StorageProfileId");

                    b.HasIndex("StorageProfileId");

                    b.ToTable("BackupTemplateStorages");
                });

            modelBuilder.Entity("CitusManager.Domain.ClusterBackupPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EncryptionEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MinuteOfHour")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("NextRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ObjectSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("RetentionMaxAgeDays")
                        .HasColumnType("integer");

                    b.Property<int>("RetentionMaxBackups")
                        .HasColumnType("integer");

                    b.Property<int>("RetentionMinBackups")
                        .HasColumnType("integer");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("RunAtLocalTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("RunOnDayOfMonth")
                        .HasColumnType("integer");

                    b.Property<int>("RunOnDayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleInterval")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleUnit")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceTemplateId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SourceTemplateVersion")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectKind")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceTemplateId");

                    b.HasIndex("ClusterId", "SubjectKind")
                        .IsUnique();

                    b.HasIndex("IsEnabled", "NextRunAt");

                    b.ToTable("ClusterBackupPolicies");
                });

            modelBuilder.Entity("CitusManager.Domain.ClusterBackupPolicyNotification", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NotificationProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Events")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("PolicyId", "NotificationProfileId");

                    b.HasIndex("NotificationProfileId");

                    b.ToTable("ClusterBackupPolicyNotification");
                });

            modelBuilder.Entity("CitusManager.Domain.ClusterBackupPolicyStorage", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StorageProfileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("PolicyId", "StorageProfileId");

                    b.HasIndex("StorageProfileId");

                    b.ToTable("ClusterBackupPolicyStorage");
                });

            modelBuilder.Entity("CitusManager.Domain.ClusterOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("PlanHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<int>("Risk")
                        .HasColumnType("integer");

                    b.Property<string>("SafeError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ClusterId", "Status");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("CitusManager.Domain.ClusterProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CapabilityJson")
                        .HasColumnType("text");

                    b.Property<string>("CitusVersion")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("PostgreSqlVersion")
                        .HasColumnType("text");

                    b.Property<string>("PrometheusBaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProtectedPassword")
                        .HasColumnType("text");

                    b.Property<string>("ProtectedPrometheusToken")
                        .HasColumnType("text");

                    b.Property<int>("SslMode")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Host", "Port", "Database")
                        .IsUnique();

                    b.ToTable("Clusters");
                });

            modelBuilder.Entity("CitusManager.Domain.ClusterQueryEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("MetadataSynced")
                        .HasColumnType("boolean");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId", "Host", "Port")
                        .IsUnique();

                    b.HasIndex("ClusterId", "IsEnabled", "Health");

                    b.ToTable("ClusterQueryEndpoints");
                });

            modelBuilder.Entity("CitusManager.Domain.MetricSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LabelsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId", "Name", "CollectedAt");

                    b.ToTable("MetricSamples");
                });

            modelBuilder.Entity("CitusManager.Domain.NotificationDelivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("BackupRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Event")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NotificationProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("NotificationProfileVersion")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RestoreRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("SafeError")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NotificationProfileId");

                    b.HasIndex("RestoreRunId");

                    b.HasIndex("BackupRunId", "NotificationProfileId", "Event");

                    b.ToTable("NotificationDeliveries");
                });

            modelBuilder.Entity("CitusManager.Domain.NotificationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("NotificationProfiles");
                });

            modelBuilder.Entity("CitusManager.Domain.NotificationProfileVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailRecipientsJson")
                        .HasColumnType("text");

                    b.Property<Guid>("NotificationProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProtectedSmtpPassword")
                        .HasColumnType("text");

                    b.Property<string>("ProtectedTelegramBotToken")
                        .HasColumnType("text");

                    b.Property<string>("SmtpFrom")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("SmtpHost")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("integer");

                    b.Property<bool>("SmtpUseTls")
                        .HasColumnType("boolean");

                    b.Property<string>("SmtpUsername")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("TelegramTargetsJson")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NotificationProfileId", "Version")
                        .IsUnique();

                    b.ToTable("NotificationProfileVersions");
                });

            modelBuilder.Entity("CitusManager.Domain.OperationStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OperationId", "Sequence")
                        .IsUnique();

                    b.ToTable("OperationSteps");
                });

            modelBuilder.Entity("CitusManager.Domain.RestoreRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BackupRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfirmationHash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentPhase")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DiagnosticTail")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSameTarget")
                        .HasColumnType("boolean");

                    b.Property<bool>("MaintenanceAcknowledged")
                        .HasColumnType("boolean");

                    b.Property<int>("ParallelJobs")
                        .HasColumnType("integer");

                    b.Property<long>("ProcessedBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ProtectedTargetConnectionJson")
                        .HasColumnType("text");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("SafeError")
                        .HasColumnType("text");

                    b.Property<Guid>("SourceClusterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TargetClusterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("TargetCredentialsExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceClusterId");

                    b.HasIndex("BackupRunId", "CreatedAt");

                    b.HasIndex("TargetClusterId", "Status");

                    b.HasIndex("TargetIdentityHash", "Status");

                    b.ToTable("RestoreRuns");
                });

            modelBuilder.Entity("CitusManager.Domain.RestoreRunStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("ProcessedBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RestoreRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("SafeError")
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long?>("TotalBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RestoreRunId", "Sequence")
                        .IsUnique();

                    b.ToTable("RestoreRunSteps");
                });

            modelBuilder.Entity("CitusManager.Domain.StorageProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StorageProfiles");
                });

            modelBuilder.Entity("CitusManager.Domain.StorageProfileVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Bucket")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GoogleDriveFolderId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LocalSubdirectory")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ObjectPrefix")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProtectedAccessKey")
                        .HasColumnType("text");

                    b.Property<string>("ProtectedGoogleClientId")
                        .HasColumnType("text");

                    b.Property<string>("ProtectedGoogleClientSecret")
                        .HasColumnType("text");

                    b.Property<string>("ProtectedGoogleRefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("ProtectedSecretKey")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("StorageProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StorageProfileId", "Version")
                        .IsUnique();

                    b.ToTable("StorageProfileVersions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CitusManager.Domain.AlertRecord", b =>
                {
                    b.HasOne("CitusManager.Domain.ClusterProfile", "Cluster")
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("CitusManager.Domain.BackupDestinationCopy", b =>
                {
                    b.HasOne("CitusManager.Domain.BackupRun", "BackupRun")
                        .WithMany("DestinationCopies")
                        .HasForeignKey("BackupRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CitusManager.Domain.StorageProfile", "StorageProfile")
                        .WithMany()
                        .HasForeignKey("StorageProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BackupRun");

                    b.Navigation("StorageProfile");
                });

            modelBuilder.Entity("CitusManager.Domain.BackupRun", b =>
                {
                    b.HasOne("CitusManager.Domain.ClusterProfile", "Cluster")
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CitusManager.Domain.ClusterBackupPolicy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CitusManager.Domain.BackupRun", "RetriedFromRun")
                        .WithMany()
                        .HasForeignKey("RetriedFromRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cluster");

                    b.Navigation("Policy");

                    b.Navigation("RetriedFromRun");
                });

            modelBuilder.Entity("CitusManager.Domain.BackupRunStep", b =>
                {
                    b.HasOne("CitusManager.Domain.BackupRun", "BackupRun")
                        .WithMany("Steps")
                        .HasForeignKey("BackupRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BackupRun");
                });

            modelBuilder.Entity("CitusManager.Domain.BackupTemplateNotification", b =>
                {
                    b.HasOne("CitusManager.Domain.NotificationProfile", "NotificationProfile")
                        .WithMany()
                        .HasForeignKey("NotificationProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CitusManager.Domain.BackupTemplate", "Template")
                        .WithMany("Notifications")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationProfile");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("CitusManager.Domain.BackupTemplateStorage", b =>
                {
                    b.HasOne("CitusManager.Domain.StorageProfile", "StorageProfile")
                        .WithMany()
                        .HasForeignKey("StorageProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CitusManager.Domain.BackupTemplate", "Template")
                        .WithMany("Storages")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StorageProfile");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("CitusManager.Domain.ClusterBackupPolicy", b =>
                {
                    b.HasOne("CitusManager.Domain.ClusterProfile", "Cluster")
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CitusManager.Domain.BackupTemplate", "SourceTemplate")
                        .WithMany()
                        .HasForeignKey("SourceTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cluster");

                    b.Navigation("SourceTemplate");
                });

            modelBuilder.Entity("CitusManager.Domain.ClusterBackupPolicyNotification", b =>
                {
                    b.HasOne("CitusManager.Domain.NotificationProfile", "NotificationProfile")
                        .WithMany()
                        .HasForeignKey("NotificationProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CitusManager.Domain.ClusterBackupPolicy", "Policy")
                        .WithMany("Notifications")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationProfile");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("CitusManager.Domain.ClusterBackupPolicyStorage", b =>
                {
                    b.HasOne("CitusManager.Domain.ClusterBackupPolicy", "Policy")
                        .WithMany("Storages")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CitusManager.Domain.StorageProfile", "StorageProfile")
                        .WithMany()
                        .HasForeignKey("StorageProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("StorageProfile");
                });

            modelBuilder.Entity("CitusManager.Domain.ClusterOperation", b =>
                {
                    b.HasOne("CitusManager.Domain.ClusterProfile", "Cluster")
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("CitusManager.Domain.ClusterQueryEndpoint", b =>
                {
                    b.HasOne("CitusManager.Domain.ClusterProfile", "Cluster")
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("CitusManager.Domain.MetricSample", b =>
                {
                    b.HasOne("CitusManager.Domain.ClusterProfile", "Cluster")
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("CitusManager.Domain.NotificationDelivery", b =>
                {
                    b.HasOne("CitusManager.Domain.BackupRun", "BackupRun")
                        .WithMany("NotificationDeliveries")
                        .HasForeignKey("BackupRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CitusManager.Domain.NotificationProfile", "NotificationProfile")
                        .WithMany()
                        .HasForeignKey("NotificationProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CitusManager.Domain.RestoreRun", "RestoreRun")
                        .WithMany("NotificationDeliveries")
                        .HasForeignKey("RestoreRunId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("BackupRun");

                    b.Navigation("NotificationProfile");

                    b.Navigation("RestoreRun");
                });

            modelBuilder.Entity("CitusManager.Domain.NotificationProfileVersion", b =>
                {
                    b.HasOne("CitusManager.Domain.NotificationProfile", "NotificationProfile")
                        .WithMany("Versions")
                        .HasForeignKey("NotificationProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationProfile");
                });

            modelBuilder.Entity("CitusManager.Domain.OperationStep", b =>
                {
                    b.HasOne("CitusManager.Domain.ClusterOperation", "Operation")
                        .WithMany("Steps")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("CitusManager.Domain.RestoreRun", b =>
                {
                    b.HasOne("CitusManager.Domain.BackupRun", "BackupRun")
                        .WithMany("RestoreRuns")
                        .HasForeignKey("BackupRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CitusManager.Domain.ClusterProfile", "SourceCluster")
                        .WithMany()
                        .HasForeignKey("SourceClusterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CitusManager.Domain.ClusterProfile", "TargetCluster")
                        .WithMany()
                        .HasForeignKey("TargetClusterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BackupRun");

                    b.Navigation("SourceCluster");

                    b.Navigation("TargetCluster");
                });

            modelBuilder.Entity("CitusManager.Domain.RestoreRunStep", b =>
                {
                    b.HasOne("CitusManager.Domain.RestoreRun", "RestoreRun")
                        .WithMany("Steps")
                        .HasForeignKey("RestoreRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RestoreRun");
                });

            modelBuilder.Entity("CitusManager.Domain.StorageProfileVersion", b =>
                {
                    b.HasOne("CitusManager.Domain.StorageProfile", "StorageProfile")
                        .WithMany("Versions")
                        .HasForeignKey("StorageProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StorageProfile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CitusManager.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CitusManager.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CitusManager.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CitusManager.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CitusManager.Domain.BackupRun", b =>
                {
                    b.Navigation("DestinationCopies");

                    b.Navigation("NotificationDeliveries");

                    b.Navigation("RestoreRuns");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("CitusManager.Domain.BackupTemplate", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Storages");
                });

            modelBuilder.Entity("CitusManager.Domain.ClusterBackupPolicy", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Storages");
                });

            modelBuilder.Entity("CitusManager.Domain.ClusterOperation", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("CitusManager.Domain.NotificationProfile", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("CitusManager.Domain.RestoreRun", b =>
                {
                    b.Navigation("NotificationDeliveries");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("CitusManager.Domain.StorageProfile", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
